## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('/content/train.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df.shape

(20800, 5)

In [6]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
###Drop Nan Values
df=df.dropna()


In [9]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [10]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [11]:
## Get the Dependent features
y=df['label']

In [12]:
X.shape

(18285, 4)

In [13]:
y.shape

(18285,)

In [14]:
import tensorflow as tf

In [15]:
tf.__version__

'2.18.0'

In [40]:
from keras.layers import Embedding #help to implement word2vec
from keras.preprocessing.sequence import pad_sequences #prepadding or postpadding
from keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from keras.layers import LSTM
from keras.layers import Dense

In [41]:
### Vocabulary size - unique words present
voc_size=5000

### Onehot Representation
#### at which index are the words present

In [42]:
messages=X.copy()

In [43]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [49]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [50]:
#messages.reset_index(inplace=True)

In [51]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [52]:
import nltk
import re #regular expression (regex)
from nltk.corpus import stopwords #(english stopwords)

In [53]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [54]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i]) #apart from a-z and A-Z, remove special characters and replace with blank
    review = review.lower() #lower all title
    review = review.split() #get words by words

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')] #if word is not in stopwords english, stem it, if present in stopwords, ignore it
    review = ' '.join(review) #join all the review
    corpus.append(review) #create the corpus

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [55]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [56]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2991, 229, 1476, 2230, 4160, 1246, 4034, 2242, 3095, 2549],
 [4618, 719, 620, 2282, 4411, 746, 1585],
 [3588, 3017, 3827, 711],
 [1938, 4942, 3473, 1611, 1288, 1549],
 [135, 4411, 1388, 4028, 543, 539, 4411, 2723, 1516, 3026],
 [4188,
  3748,
  4392,
  7,
  1902,
  4828,
  1759,
  4628,
  1438,
  325,
  1807,
  2288,
  2289,
  320,
  1585],
 [2699, 4302, 1451, 2175, 3622, 2780, 2405, 3848, 3392, 898, 4417],
 [1510, 87, 3215, 2253, 2194, 2656, 4828, 3033, 3392, 898, 4417],
 [3362, 4126, 4822, 2365, 2323, 1691, 4538, 3765, 4828, 2598],
 [1244, 2091, 255, 2329, 2968, 4696, 3896, 761],
 [1863, 2774, 3320, 2533, 671, 323, 4989, 2804, 4425, 4100, 2631],
 [1611, 2394, 4160, 1691, 4828, 2194],
 [2811, 4513, 4714, 576, 277, 1409, 3593, 1987, 2284],
 [2378, 1649, 1117, 2883, 4900, 4330, 4512, 3392, 898, 4417],
 [3507, 193, 687, 3414, 4362, 3392, 898, 4417],
 [224, 3281, 2978, 2629, 1872, 4334, 4250, 382, 4545, 4983],
 [2023, 839, 719],
 [978, 3243, 2994, 1765, 4828, 1430, 1543, 1585],
 [2491, 

In [57]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [58]:
onehot_repr[1]

[4618, 719, 620, 2282, 4411, 746, 1585]

### Embedding Representation
#### Word2vec representation

In [59]:
#length of all sentences should be same
sent_length=20 #value should cover length of all the sentences
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length) #add zeros at the end of the sentences #postpadding
print(embedded_docs)

[[2991  229 1476 ...    0    0    0]
 [4618  719  620 ...    0    0    0]
 [3588 3017 3827 ...    0    0    0]
 ...
 [ 229 4760   11 ...    0    0    0]
 [2857 2194 4738 ...    0    0    0]
 [2184 2861 2015 ...    0    0    0]]


In [60]:
embedded_docs[1] #20 values - length of all sentences should be 20

array([4618,  719,  620, 2282, 4411,  746, 1585,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [61]:
embedded_docs[0]

array([2991,  229, 1476, 2230, 4160, 1246, 4034, 2242, 3095, 2549,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [64]:
## Creating model - apply embedding and LSTM layer
embedding_vector_features=40 ##features representation -each word at particular index will be converted by a vector of size 40, every word will be represented by a 40-dimensional vector
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features, input_length=sent_length)) #voc_size=5000,embedding_vector_features=40,input_length=20
model.add(LSTM(100)) #100 neurons
model.add(Dense(1,activation='sigmoid')) #output is binary, thus activation function is sigmoid
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy']) #binary output - binary_crossentropy

In [65]:
model.build(input_shape=(None, sent_length))
print(model.summary())

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ (None, 20, 40)              │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_4 (LSTM)                        │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [66]:
len(embedded_docs),y.shape

(18285, (18285,))

In [67]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [68]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [78]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7370 - loss: 0.4525 - val_accuracy: 0.9171 - val_loss: 0.1913
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.9438 - loss: 0.1432 - val_accuracy: 0.9157 - val_loss: 0.1966
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9633 - loss: 0.1026 - val_accuracy: 0.9253 - val_loss: 0.2068
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.9736 - loss: 0.0813 - val_accuracy: 0.9201 - val_loss: 0.2515
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9800 - loss: 0.0586 - val_accuracy: 0.9114 - val_loss: 0.2203
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9837 - loss: 0.0557 - val_accuracy: 0.9173 - val_loss: 0.3144
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9877 - loss: 0.0359 - val_accuracy: 0.9089 - val_loss: 0.3480
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9899 - loss: 0.0285 - val_accur

### Adding Dropout

In [77]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3)) #30% of the LSTM while training will be disabled. also drop out reduces overfitting
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


### Performance Metrics And Accuracy

In [79]:
y_pred=model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [80]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve #1-fake news and 0-not fake news

In [81]:
from sklearn.metrics import confusion_matrix

In [82]:
confusion_matrix(y_test,y_pred)

array([[3119,  300],
       [ 229, 2387]])

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9123446561723281

In [84]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.89      0.91      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

