### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=11

#### One Hot Representation

In [ ]:
# Capture indexing which is 1. Index 128 equals to 'the'
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[9, 6, 5, 3], [9, 6, 5, 1], [9, 6, 5, 9], [3, 1, 3, 9, 6], [3, 1, 3, 9, 6], [7, 9, 1, 5, 5], [4, 2, 5, 9]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences #sentences have different length, need to use padding
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
## pre padding will make all the sentences length become 8 (add zeros to the first part of the sentence - pre padding)
sent_length= 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[0 0 0 0 9 6 5 3]
 [0 0 0 0 9 6 5 1]
 [0 0 0 0 9 6 5 9]
 [0 0 0 3 1 3 9 6]
 [0 0 0 3 1 3 9 6]
 [0 0 0 7 9 1 5 5]
 [0 0 0 0 4 2 5 9]]


In [ ]:
## 10 feature dimensions
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim)) # dim is how many dimension mentioned earlier which is 10
model.compile(optimizer='adam',loss='mse')

In [ ]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)             │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
##'the glass of milk',
embedded_docs[0]

array([0, 0, 0, 0, 9, 6, 5, 3], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step


array([[-0.03308151,  0.03128393, -0.02975135, -0.00050538, -0.01632291,
        -0.01135323,  0.01105142, -0.0058804 ,  0.03982874,  0.01650277],
       [-0.03308151,  0.03128393, -0.02975135, -0.00050538, -0.01632291,
        -0.01135323,  0.01105142, -0.0058804 ,  0.03982874,  0.01650277],
       [-0.03308151,  0.03128393, -0.02975135, -0.00050538, -0.01632291,
        -0.01135323,  0.01105142, -0.0058804 ,  0.03982874,  0.01650277],
       [-0.03308151,  0.03128393, -0.02975135, -0.00050538, -0.01632291,
        -0.01135323,  0.01105142, -0.0058804 ,  0.03982874,  0.01650277],
       [ 0.03445461, -0.03690361,  0.04685085, -0.02928423,  0.00387688,
         0.04557757, -0.01838265, -0.04564491,  0.0114092 ,  0.01800516],
       [ 0.02033451,  0.04527969,  0.00818772, -0.00513726,  0.03568313,
         0.01761607, -0.00628207,  0.00380693, -0.03162567, -0.02534582],
       [-0.00135931, -0.00943565,  0.00330972,  0.00026638, -0.02256165,
         0.0179139 , -0.04773719,  0.00835843

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]